name: Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Check CDK Bootstrap Status
      run: |
        echo "Checking if CDK is already bootstrapped..."
        if aws cloudformation describe-stacks --stack-name CDKToolkit --region ${{ env.AWS_REGION }} 2>/dev/null; then
          echo "CDK is already bootstrapped"
          echo "BOOTSTRAPPED=true" >> $GITHUB_ENV
        else
          echo "CDK is not bootstrapped"
          echo "BOOTSTRAPPED=false" >> $GITHUB_ENV
        fi

    - name: CDK Bootstrap (if needed)
      if: env.BOOTSTRAPPED == 'false'
      run: |
        echo "Bootstrapping CDK environment..."
        cdk bootstrap aws://$(aws sts get-caller-identity --query Account --output text)/${{ env.AWS_REGION }} || {
          echo "Bootstrap failed. This might be due to insufficient permissions."
          echo "Please ensure your AWS credentials have the following permissions:"
          echo "- CloudFormation: CreateStack, DeleteStack, DescribeStacks"
          echo "- IAM: CreateRole, DeleteRole, AttachRolePolicy, DetachRolePolicy"
          echo "- S3: CreateBucket, DeleteBucket, PutObject, GetObject"
          echo "- SSM: PutParameter, GetParameter, DeleteParameter"
          echo "- ECR: CreateRepository, DeleteRepository"
          echo "Bootstrap is required for deployment. Exiting..."
          exit 1
        }

    - name: Deploy with CDK
      run: |
        echo "Deploying CDK stack..."
        npm run deploy -- --require-approval never || {
          echo "Deployment failed. Checking if bootstrap is the issue..."
          if ! aws ssm get-parameter --name "/cdk-bootstrap/hnb659fds/version" --region ${{ env.AWS_REGION }} 2>/dev/null; then
            echo "Bootstrap parameter not found. Attempting to bootstrap now..."
            cdk bootstrap aws://$(aws sts get-caller-identity --query Account --output text)/${{ env.AWS_REGION }} || {
              echo "Bootstrap failed. Please ensure your AWS credentials have sufficient permissions."
              echo "Required permissions: CloudFormation, IAM, S3, SSM, ECR"
              exit 1
            }
            echo "Bootstrap successful. Retrying deployment..."
            npm run deploy -- --require-approval never
          else
            echo "Bootstrap exists but deployment still failed. Check the error above."
            exit 1
          fi
        }
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Output deployment info
      run: |
        echo "Deployment completed successfully!"
        echo "Check AWS Console for Lambda function and S3 trigger setup."